# Generated by Django 4.1.2 on 2022-10-27 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_photo_created_at_photo_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='hero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.hero'),
        ),
    ]
